### ISSUE TITLE
general style

### ISSUE THREAD

**Issue by giuliobosco** [CSAGermoglio/CSAGermoglio.github.io#1]
- [x] remove all green backgrounds
- [x] titles writes with the green given color
- [x] create a max-width of 900 px (so all photos and text is left aligned to the inner container of 900 px max width)
- [x] align titles left

**Comment by Sbovo01** [comment]
done in 0b90544

**Comment by giuliobosco** [comment]
- [x] center the container with max-width 900px
- [x] the titles  ( like "Agricoltura partecipativa CSA Germoglio") remove the "CSA Germoglio" and use h2 for the other piece of the title.

**Comment by Sbovo01** [comment]
Done in 22259e7
