### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by giuliobosco** [CSAGermoglio/CSAGermoglio.github.io#2]
- [x] remove the title "Contatti CSA Germoglio" and replace with a blank space
- [x] footer with the green background (the color have to be the dark color used in titles now)
  - [x] desktop on a single line left "CSA Germoglio" middle the phone number (without icon) and right the email address as link without the icon
  - [x] mobile centered one bellow the other in the same order and same properties

**Comment by Sbovo01** [comment]
done in 0b90544

**Comment by giuliobosco** [comment]
- [x] create a margin above the footer of white space.
- [x] reduce the hight of the footer
- [x] do not keep all upper case in the footer.

**Comment by Sbovo01** [comment]
done in da40a51
