### ISSUE TITLE
update 13.03.2022 - fix

### ISSUE THREAD

**Issue by giuliobosco** [CSAGermoglio/CSAGermoglio.github.io#5]
- [x] Social networks Images smaller
- [x] Fix first two donwload links (as in email, before "Agricoltura partecipativa")
- [x] Then the "statuto" before the footer
- [x] on iphones the phone number and the iban (in the footer) are colored in blue should be all in white

**Comment by FadilSmajilbasic** [comment]
Solved all the issues

**Comment by FadilSmajilbasic** [comment]
@giuliobosco fixed additional issues in [SHA-5b269ad32a2a19f634df671170b9dd764692ff3e](https://github.com/CSAGermoglio/CSAGermoglio.github.io/commit/5b269ad32a2a19f634df671170b9dd764692ff3e)
